// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm1Xob97wtBMybtVhyqdRpKxyYE5-ORfk',
    appId: '1:858734993308:web:729a969307545e28dd7259',
    messagingSenderId: '858734993308',
    projectId: 'web-rtc-riverpod',
    authDomain: 'web-rtc-riverpod.firebaseapp.com',
    storageBucket: 'web-rtc-riverpod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8AOKYpZ4klOZf0THFvSyPHXOQdO9AJm0',
    appId: '1:858734993308:android:8da82426731e3ac1dd7259',
    messagingSenderId: '858734993308',
    projectId: 'web-rtc-riverpod',
    storageBucket: 'web-rtc-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY9x2AgvNx0wDLUCaTVHmtCILOyOdd1Dk',
    appId: '1:858734993308:ios:caa8f2c8fd590d3ddd7259',
    messagingSenderId: '858734993308',
    projectId: 'web-rtc-riverpod',
    storageBucket: 'web-rtc-riverpod.appspot.com',
    iosClientId: '858734993308-f51tm504bh89a8n0g2eem5jtba1cuqr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodWebRtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY9x2AgvNx0wDLUCaTVHmtCILOyOdd1Dk',
    appId: '1:858734993308:ios:caa8f2c8fd590d3ddd7259',
    messagingSenderId: '858734993308',
    projectId: 'web-rtc-riverpod',
    storageBucket: 'web-rtc-riverpod.appspot.com',
    iosClientId: '858734993308-f51tm504bh89a8n0g2eem5jtba1cuqr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodWebRtc',
  );
}
